# PlatformIO pre-build step: gzip pc/web/index.html into src/web_gz.h so the ESP32
# serves the exact same dashboard as the PC hub.
import gzip
from pathlib import Path

try:
    Import("env")  # noqa: F821  (provided by PlatformIO/SCons)
    root = Path(env["PROJECT_DIR"])  # noqa: F821
except NameError:
    root = Path(__file__).parent

src = root.parent / "pc" / "web" / "index.html"
out = root / "src" / "web_gz.h"
data = gzip.compress(src.read_bytes(), compresslevel=9, mtime=0)
lines = [", ".join(f"0x{b:02x}" for b in data[i:i + 24]) for i in range(0, len(data), 24)]
body = (
    "// Generated by embed_web.py from pc/web/index.html. Do not edit.\n#pragma once\n#include <Arduino.h>\n"
    f"static const size_t WEB_GZ_LEN = {len(data)};\n"
    "static const uint8_t WEB_GZ[] PROGMEM = {\n  " + ",\n  ".join(lines) + "\n};\n"
)
if not out.exists() or out.read_text() != body:
    out.write_text(body)
print(f"embed_web: {src.name} -> {out.name} ({len(data)} bytes gzipped)")
