[env:esp32dev]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts = pre:embed_web.py
lib_deps =
    tzapu/WiFiManager@^2.0.17
